Auto mode
xaviertorgerson/micromouse pull request #124
Opened 2017-03-20 03:04 UTC by asaba96

Works on robot. Very robust, in that it remembers the number of runs and state (error/no error).

I would like to add speed control (speed goes up/down depending on state/number runs)

In addition, Aaron had an idea of if we don't know best path, it keeps searching instead of going back to (0,0) so we don't waste a run on another search.

2017-03-20 03:06 UTC, asaba96 commented
In addition, as it is currently written, auto mode is on by default. We also need to set the target locations for APAC in conf.h (currently I have it set to (4,4)) and find a robust speed we want to set search and kaos at.

2017-03-20 19:24 UTC, ghost requested changes
Change/add the following (also made some comments on the diff):
 - Whitespace style - Change your tabs to spaces.
 - Spelling - It's APEC, not APAC :-)
 - Pauses - Like you mentioned before, we need the one-second pause in the start square to comply with the rules.

 - Question - What is maze clear? What advantage does that have over regular clear?

I haven't read through the logic of `autoMode()`, `autoRun()`, and `autoKaos()`, but I did test on the bot myself and it works pretty great. We do crash, but that's because motion sucks :-)

When we do crash, I tested turning the bot off, moving it back to the start, turning it back on, and resuming auto mode. And it works great. Nice job!!

2017-03-20 19:24 UTC, ryanpitt commented on src/conf.h
> +#define APAC_TARGET_Y 4
The competition maze is 16x16, and the finish is the middle 4 squares. So (7, 7) or (8, 8) would work. I think in the past we did (7, 7).

2017-03-20 19:24 UTC, ryanpitt commented on src/conf.h
> +#define APAC_TARGET_Y 4
Here and in other places, the spelling is APEC, not APAC.

2017-03-20 19:24 UTC, ryanpitt commented on src/conf.h
> +#define EEPROM_STATE_LOCATION 522
Are these safe locations? Why the message?

2017-03-20 19:24 UTC, ryanpitt commented on src/main.cpp
> +	PersistantStorage::setTargetYLocation(APAC_TARGET_Y);
I would argue that we can remove this. We can upload old code to set any target location we want, and then upload the auto mode code which won't allow us to change the location anymore. In my eyes that's a good enough solution and gives us maximum flexibility for testing.

2017-03-20 19:24 UTC, ryanpitt commented on src/conf.h
> +#define APAC_TARGET_Y 4
And see my other message about how we might not even need this setting.

2017-03-20 19:27 UTC, asaba96 commented
So the maze clear function clears the maze but doesn't reset numRuns and state. This is key if we see our kaos fails a lot. Often doing a maze clear and doing another run fixes the issues with Kaos crashing constantly.

2017-03-20 19:29 UTC, asaba96 commented
I will fix the issues mentioned and commit those fixes. In addition, I forgot to take out comments I left for myself. Apologies for bad styling.

2017-03-20 19:30 UTC, asaba96 commented on src/conf.h
> +#define EEPROM_STATE_LOCATION 522
These are safe locations. The message was for myself. I will remove it.

2017-03-25 03:27 UTC, ryanpitt commented
Took executive action. Rebased, added to, and merged separately.

2017-03-25 03:27 UTC, closed without merging